#!/usr/bin/env python
from __future__ import print_function
import sys


def train():
    print('Starting the training.')
    print('Training complete.')

if __name__ == '__main__':
    train()

    # A zero exit code causes the job to be marked a Succeeded.
    sys.exit(0)
